# ─────────────────────────────────────────────────────────────
# 1) 사이트 일반 설정
# ─────────────────────────────────────────────────────────────
title: "MinSu Ko"      # 블로그 제목 (원하는 대로 수정)
description: "나의 개인 블로그"   # 간략 설명
baseurl: ""                    # 리포지토리 이름을 붙이지 않을 경우 빈 문자열
url: "https://minsu-ko.github.io"  
#  → 반드시 YOUR_USERNAME과 YOUR_REPO를 실제 GitHub 계정명 및 리포지토리명으로 변경하세요.

# ─────────────────────────────────────────────────────────────
# 2) 기타 Jekyll 옵션
# ─────────────────────────────────────────────────────────────
theme: null                    # 커스텀 레이아웃을 사용할 예정이므로 null
markdown: kramdown
lang: ko                       # 기본 언어를 한국어로 설정
plugins: []                    # 플러그인 사용 필요 시 추가

# ─────────────────────────────────────────────────────────────
# 3) 포스트(permalink) 형식 지정 (옵션)
# ─────────────────────────────────────────────────────────────
permalink: /:categories/:year/:month/:day/:title.html
